/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindDownRouteImport } from './routes/wind-down'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WindDownStoryRouteImport } from './routes/wind-down_.story'
import { Route as WindDownMusicRouteImport } from './routes/wind-down_.music'
import { Route as WindDownBreathingRouteImport } from './routes/wind-down_.breathing'
import { Route as SleepSummaryRouteImport } from './routes/sleep_.summary'
import { Route as SleepQualityRouteImport } from './routes/sleep_.quality'

const WindDownRoute = WindDownRouteImport.update({
  id: '/wind-down',
  path: '/wind-down',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WindDownStoryRoute = WindDownStoryRouteImport.update({
  id: '/wind-down_/story',
  path: '/wind-down/story',
  getParentRoute: () => rootRouteImport,
} as any)
const WindDownMusicRoute = WindDownMusicRouteImport.update({
  id: '/wind-down_/music',
  path: '/wind-down/music',
  getParentRoute: () => rootRouteImport,
} as any)
const WindDownBreathingRoute = WindDownBreathingRouteImport.update({
  id: '/wind-down_/breathing',
  path: '/wind-down/breathing',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepSummaryRoute = SleepSummaryRouteImport.update({
  id: '/sleep_/summary',
  path: '/sleep/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepQualityRoute = SleepQualityRouteImport.update({
  id: '/sleep_/quality',
  path: '/sleep/quality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/stats': typeof StatsRoute
  '/wind-down': typeof WindDownRoute
  '/sleep/quality': typeof SleepQualityRoute
  '/sleep/summary': typeof SleepSummaryRoute
  '/wind-down/breathing': typeof WindDownBreathingRoute
  '/wind-down/music': typeof WindDownMusicRoute
  '/wind-down/story': typeof WindDownStoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/stats': typeof StatsRoute
  '/wind-down': typeof WindDownRoute
  '/sleep/quality': typeof SleepQualityRoute
  '/sleep/summary': typeof SleepSummaryRoute
  '/wind-down/breathing': typeof WindDownBreathingRoute
  '/wind-down/music': typeof WindDownMusicRoute
  '/wind-down/story': typeof WindDownStoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/stats': typeof StatsRoute
  '/wind-down': typeof WindDownRoute
  '/sleep_/quality': typeof SleepQualityRoute
  '/sleep_/summary': typeof SleepSummaryRoute
  '/wind-down_/breathing': typeof WindDownBreathingRoute
  '/wind-down_/music': typeof WindDownMusicRoute
  '/wind-down_/story': typeof WindDownStoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/auth'
    | '/focus'
    | '/onboarding'
    | '/plan'
    | '/settings'
    | '/sleep'
    | '/stats'
    | '/wind-down'
    | '/sleep/quality'
    | '/sleep/summary'
    | '/wind-down/breathing'
    | '/wind-down/music'
    | '/wind-down/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/auth'
    | '/focus'
    | '/onboarding'
    | '/plan'
    | '/settings'
    | '/sleep'
    | '/stats'
    | '/wind-down'
    | '/sleep/quality'
    | '/sleep/summary'
    | '/wind-down/breathing'
    | '/wind-down/music'
    | '/wind-down/story'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/auth'
    | '/focus'
    | '/onboarding'
    | '/plan'
    | '/settings'
    | '/sleep'
    | '/stats'
    | '/wind-down'
    | '/sleep_/quality'
    | '/sleep_/summary'
    | '/wind-down_/breathing'
    | '/wind-down_/music'
    | '/wind-down_/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AuthRoute: typeof AuthRoute
  FocusRoute: typeof FocusRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  SettingsRoute: typeof SettingsRoute
  SleepRoute: typeof SleepRoute
  StatsRoute: typeof StatsRoute
  WindDownRoute: typeof WindDownRoute
  SleepQualityRoute: typeof SleepQualityRoute
  SleepSummaryRoute: typeof SleepSummaryRoute
  WindDownBreathingRoute: typeof WindDownBreathingRoute
  WindDownMusicRoute: typeof WindDownMusicRoute
  WindDownStoryRoute: typeof WindDownStoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wind-down': {
      id: '/wind-down'
      path: '/wind-down'
      fullPath: '/wind-down'
      preLoaderRoute: typeof WindDownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wind-down_/story': {
      id: '/wind-down_/story'
      path: '/wind-down/story'
      fullPath: '/wind-down/story'
      preLoaderRoute: typeof WindDownStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wind-down_/music': {
      id: '/wind-down_/music'
      path: '/wind-down/music'
      fullPath: '/wind-down/music'
      preLoaderRoute: typeof WindDownMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wind-down_/breathing': {
      id: '/wind-down_/breathing'
      path: '/wind-down/breathing'
      fullPath: '/wind-down/breathing'
      preLoaderRoute: typeof WindDownBreathingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep_/summary': {
      id: '/sleep_/summary'
      path: '/sleep/summary'
      fullPath: '/sleep/summary'
      preLoaderRoute: typeof SleepSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep_/quality': {
      id: '/sleep_/quality'
      path: '/sleep/quality'
      fullPath: '/sleep/quality'
      preLoaderRoute: typeof SleepQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AuthRoute: AuthRoute,
  FocusRoute: FocusRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  SettingsRoute: SettingsRoute,
  SleepRoute: SleepRoute,
  StatsRoute: StatsRoute,
  WindDownRoute: WindDownRoute,
  SleepQualityRoute: SleepQualityRoute,
  SleepSummaryRoute: SleepSummaryRoute,
  WindDownBreathingRoute: WindDownBreathingRoute,
  WindDownMusicRoute: WindDownMusicRoute,
  WindDownStoryRoute: WindDownStoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
