/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SleepSummaryRouteImport } from './routes/sleep.summary'
import { Route as SleepQualityRouteImport } from './routes/sleep.quality'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepSummaryRoute = SleepSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => SleepRoute,
} as any)
const SleepQualityRoute = SleepQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => SleepRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/sleep': typeof SleepRouteWithChildren
  '/stats': typeof StatsRoute
  '/sleep/quality': typeof SleepQualityRoute
  '/sleep/summary': typeof SleepSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/sleep': typeof SleepRouteWithChildren
  '/stats': typeof StatsRoute
  '/sleep/quality': typeof SleepQualityRoute
  '/sleep/summary': typeof SleepSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/sleep': typeof SleepRouteWithChildren
  '/stats': typeof StatsRoute
  '/sleep/quality': typeof SleepQualityRoute
  '/sleep/summary': typeof SleepSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/auth'
    | '/focus'
    | '/onboarding'
    | '/plan'
    | '/sleep'
    | '/stats'
    | '/sleep/quality'
    | '/sleep/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/auth'
    | '/focus'
    | '/onboarding'
    | '/plan'
    | '/sleep'
    | '/stats'
    | '/sleep/quality'
    | '/sleep/summary'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/auth'
    | '/focus'
    | '/onboarding'
    | '/plan'
    | '/sleep'
    | '/stats'
    | '/sleep/quality'
    | '/sleep/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AuthRoute: typeof AuthRoute
  FocusRoute: typeof FocusRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  SleepRoute: typeof SleepRouteWithChildren
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep/summary': {
      id: '/sleep/summary'
      path: '/summary'
      fullPath: '/sleep/summary'
      preLoaderRoute: typeof SleepSummaryRouteImport
      parentRoute: typeof SleepRoute
    }
    '/sleep/quality': {
      id: '/sleep/quality'
      path: '/quality'
      fullPath: '/sleep/quality'
      preLoaderRoute: typeof SleepQualityRouteImport
      parentRoute: typeof SleepRoute
    }
  }
}

interface SleepRouteChildren {
  SleepQualityRoute: typeof SleepQualityRoute
  SleepSummaryRoute: typeof SleepSummaryRoute
}

const SleepRouteChildren: SleepRouteChildren = {
  SleepQualityRoute: SleepQualityRoute,
  SleepSummaryRoute: SleepSummaryRoute,
}

const SleepRouteWithChildren = SleepRoute._addFileChildren(SleepRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AuthRoute: AuthRoute,
  FocusRoute: FocusRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  SleepRoute: SleepRouteWithChildren,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
